$(function() {

  var citys = ["臺北市", "新北市", "台中市", "臺南市", "高雄市", "基隆市", "桃園市", "新竹市", "新竹縣", "苗栗縣", "彰化縣", "南投縣", "雲林縣", "嘉義市", "嘉義縣", "屏東縣", "宜蘭縣", "花蓮縣", "台東縣", "澎湖縣", "金門縣", "連江縣"];
  var citys_en = ["Taibei City", "New Taipei City  ", "Taichung City", "Tainan City ", "Kaohsiung City", "Keelung City", "Taoyuan City", "Hsinchu City", "Hsinchu County", "Miaoli County", "Changhua County", "Nantou County", "Yunlin County", "Chiayi City", "Chiayi County", "Pingtung County", "Yilan County ", "Hualien County", "Taitung County", "Penghu County", "Kinmen County", "Lienchiang "];
  $.getWeatherJSON = function(url, callback) {
    $.getJSON(url, function(data) {
            if (data && data.query && data.query.results && data.query.results.channel.item.forecast && data.query.results.channel.item.forecast[3] ) { // if data.query.results exist , do the following action.
              callback(data)
            } else {
              console.info("reloading : ", url)
              $.getWeatherJSON(url, callback)
            }
          })
  }
/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/

var addskycons = function(text) {
        switch (text) {
            case "Breezy":
                return Skycons.WIND
                break;

            case "Scattered Thunderstorms":
                return Skycons.CLOUDY
                break;

            case "Rain":
                return Skycons.RAIN
                break;

            case "Scattered Showers":
                return Skycons.RAIN
                break;

            case "Sunny":
                return Skycons.CLEAR_DAY
                break;

            case "Cloudy":
                return Skycons.CLOUDY
                break;

            case "Partly Cloudy":
                return Skycons.PARTLY_CLOUDY_DAY
                break;

            case "Mostly Cloudy":
                return Skycons.CLOUDY
                break;

            case "Rain And Snow":
                return Skycons.SLEET
                break;

            case "Thunderstorms":
                return Skycons.CLOUDY
                break;

            case "Mostly Sunny":
                return Skycons.CLEAR_DAY
                break;

            case "Showers":
                return Skycons.RAIN
                break;

            default:
                return null;
        }
    }
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  // skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  // skycons.add("day1", Skycons.CLEAR_DAY);
  // skycons.add("day2", Skycons.CLOUDY);
  // skycons.add("day3", Skycons.RAIN);

  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  // skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);




   
   $.getWeatherJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taipei city%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
    // 可以比較方便找到你要的資料在這個物件的哪個位置
    

    // 例如如果要拿取該縣市的目前溫度。
    
    var currentTemperature = data.query.results.channel.item.condition.temp  ;
    var currentTemperatureC = Math.round( (currentTemperature-32)*5/9 )  ;
    $('.temperature').html(currentTemperatureC);

    var CurrentDate = data.query.results.channel.item.forecast[0].date ;
    var CurrentText = data.query.results.channel.item.condition.text ;
    $('.condition').html('<span class="date">' + CurrentDate + '</span>:' + CurrentText);
    skycons.set("today", addskycons(CurrentText));

    var day1 = data.query.results.channel.item.forecast[1].date ;
    var day1Text = data.query.results.channel.item.forecast[1].text ;
    var day1High = data.query.results.channel.item.forecast[1].high ;
    var day1Low = data.query.results.channel.item.forecast[1].low ;
    var day1HighC = Math.round( (day1High-32)*5/9 ) ;
    var day1LowC = Math.round( (day1Low-32)*5/9 ) ;
    $('#date1').html(day1);
    $('#date1T').html(day1LowC + "-" + day1HighC + "&#8451");
    skycons.set("day1", addskycons(day1Text));

    var day2 = data.query.results.channel.item.forecast[2].date ;
    var day2Text = data.query.results.channel.item.forecast[2].text ;
    var day2High = data.query.results.channel.item.forecast[2].high ;
    var day2Low = data.query.results.channel.item.forecast[2].low ;
    var day2HighC = Math.round( (day2High-32)*5/9 ) ;
    var day2LowC = Math.round( (day2Low-32)*5/9 ) ;
    $('#date2').html(day2);
    $('#date2T').html(day2LowC + "-" + day2HighC + "&#8451");
    skycons.set("day2", addskycons(day2Text));

    var day3 = data.query.results.channel.item.forecast[3].date ;
    var day3Text = data.query.results.channel.item.forecast[3].text ;
    var day3High = data.query.results.channel.item.forecast[3].high ;
    var day3Low = data.query.results.channel.item.forecast[3].low ;
    var day3HighC = Math.round( (day3High-32)*5/9 ) ;
    var day3LowC = Math.round( (day3Low-32)*5/9 ) ;
    $('#date3').html(day3);
    $('#date3T').html(day3LowC + "-" + day3HighC + "&#8451");
    skycons.set("day3", addskycons(day3Text));



    
      

  })


  $.each(citys , function(index, value){
    $("#dropdown").append('<li role="presentation"><a role="menuitem" tabindex="-1" href="#" id="' + index + '" >'+ value + '</a></li>');
    $.getWeatherJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+citys_en[index]+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
    // 可以比較方便找到你要的資料在這個物件的哪個位置
    

    // 例如如果要拿取該縣市的目前溫度。
    
    var currentTemperature = data.query.results.channel.item.condition.temp  ;
    var currentTemperatureC = Math.round( (currentTemperature-32)*5/9 ) + "&#8451" ;
     $('#' + index).append('<span style="float:right">' + currentTemperatureC + '</span>');

  })
  })

/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
  $( "button" ).html( $(this).text() );
   var id = $(this).children().attr('id');
   $.getWeatherJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+citys_en[id]+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
    // 可以比較方便找到你要的資料在這個物件的哪個位置
    

    // 例如如果要拿取該縣市的目前溫度。
    
    var currentTemperature = data.query.results.channel.item.condition.temp  ;
    var currentTemperatureC = Math.round( (currentTemperature-32)*5/9 )  ;
    $('.temperature').html(currentTemperatureC);

    var CurrentDate = data.query.results.channel.item.forecast[0].date ;
    var CurrentText = data.query.results.channel.item.condition.text ;
    $('.condition').html('<span class="date">' + CurrentDate + '</span>:' + CurrentText);
    skycons.set("today", addskycons(CurrentText));

    var day1 = data.query.results.channel.item.forecast[1].date ;
    var day1Text = data.query.results.channel.item.forecast[1].text ;
    var day1High = data.query.results.channel.item.forecast[1].high ;
    var day1Low = data.query.results.channel.item.forecast[1].low ;
    var day1HighC = Math.round( (day1High-32)*5/9 ) ;
    var day1LowC = Math.round( (day1Low-32)*5/9 ) ;
    $('#date1').html(day1);
    $('#date1T').html(day1LowC + "-" + day1HighC + "&#8451");
    skycons.set("day1", addskycons(day1Text));

    var day2 = data.query.results.channel.item.forecast[2].date ;
    var day2Text = data.query.results.channel.item.forecast[2].text ;
    var day2High = data.query.results.channel.item.forecast[2].high ;
    var day2Low = data.query.results.channel.item.forecast[2].low ;
    var day2HighC = Math.round( (day2High-32)*5/9 ) ;
    var day2LowC = Math.round( (day2Low-32)*5/9 ) ;
    $('#date2').html(day2);
    $('#date2T').html(day2LowC + "-" + day2HighC + "&#8451");
    skycons.set("day2", addskycons(day2Text));

    var day3 = data.query.results.channel.item.forecast[3].date ;
    var day3Text = data.query.results.channel.item.forecast[3].text ;
    var day3High = data.query.results.channel.item.forecast[3].high ;
    var day3Low = data.query.results.channel.item.forecast[3].low ;
    var day3HighC = Math.round( (day3High-32)*5/9 ) ;
    var day3LowC = Math.round( (day3Low-32)*5/9 ) ;
    $('#date3').html(day3);
    $('#date3T').html(day3LowC + "-" + day3HighC + "&#8451");
    skycons.set("day3", addskycons(day3Text));



    
      

  })
});

}())